export const productCategories = [
  {
    path: "/center-piece",
    name: "Center Piece",
    pic: "./centerPiece.jpg",
    id: 1,
  },
  {
    path: "/clocks",
    name: "Clocks",
    pic: "./clocks.jpg",
    id: 2,
  },
  {
    path: "/lighting",
    name: "Lighting",
    pic: "./lighting.jpg",
    id: 3,
  },
  {
    path: "/mirrors",
    name: "Mirrors",
    pic: "./mirrors.jpg",
    id: 4,
  },
  {
    path: "/porcelain",
    name: "Porcelain",
    pic: "porcelain.jpg",
    id: 5,
  },
  {
    path: "/paintings",
    name: "Paintings",
    pic: "./painting.jpg",
    id: 6,
  },
  {
    path: "/seating",
    name: "Seating",
    pic: "./seating.jpg",
    id: 7,
  },
  {
    path: "/storage",
    name: "Storage",
    pic: "./storage.jpg",
    id: 8,
  },
  {
    path: "/sculpture",
    name: "Sculpture",
    pic: "./sculpture.jpg",
    id: 9,
  },
  {
    path: "/silverwave",
    name: "Silverwave",
    pic: "Silverware.jpg",
    id: 10,
  },
  {
    path: "/tables",
    name: "Tables",
    pic: "./tables.jpg",
    id: 11,
  },
  {
    path: "/dining-room",
    name: "Dining Room",
    pic: "./diningRoom.jpg",
    id: 12,
  },
  {
    path: "/living-room",
    name: "Living Room",
    pic: "./livingRoom.jpg",
    id: 13,
  },
  {
    path: "/marbles",
    name: "Marbles",
    pic: "./marbles.jpg",
    id: 14,
  },
  {
    path: "/bed-room",
    name: "Bed Room",
    pic: "./bedroom.jpg",
    id: 15,
  },
  {
    path: "/crystal",
    name: "Crystal",
    pic: "./crystal.jpg",
    id: 16,
  },
];

export const lighting = [
  {
    id: 1,
    name: "",
    pic: "/public/Products/Lighting/1.jpg",
    path: "",
  },
  {
    id: 2,
    name: "",
    pic: "/public/Products/Lighting/2.jpg",
    path: "",
  },
  {
    id: 3,
    name: "",
    pic: "/public/Products/Lighting/3.jpg",
    path: "",
  },
  {
    id: 4,
    name: "",
    pic: "/public/Products/Lighting/4.jpg",
    path: "",
  },
  {
    id: 5,
    name: "",
    pic: "/public/Products/Lighting/5.jpg",
    path: "",
  },
  {
    id: 6,
    name: "",
    pic: "/public/Products/Lighting/6.jpg",
    path: "",
  },
  {
    id: 7,
    name: "",
    pic: "/public/Products/Lighting/7.jpg",
    path: "",
  },
  {
    id: 8,
    name: "",
    pic: "/public/Products/Lighting/8.jpg",
    path: "",
  },
  {
    id: 9,
    name: "",
    pic: "/public/Products/Lighting/9.jpg",
    path: "",
  },
  {
    id: 10,
    name: "",
    pic: "/public/Products/Lighting/10.jpg",
    path: "",
  },
  {
    id: 11,
    name: "",
    pic: "/public/Products/Lighting/11.jpg",
    path: "",
  },
  {
    id: 12,
    name: "",
    pic: "/public/Products/Lighting/12.jpg",
    path: "",
  },
  {
    id: 13,
    name: "",
    pic: "/public/Products/Lighting/13.jpg",
    path: "",
  },
  {
    id: 14,
    name: "",
    pic: "/public/Products/Lighting/14.jpg",
    path: "",
  },
  {
    id: 15,
    name: "",
    pic: "/public/Products/Lighting/15.jpg",
    path: "",
  },
  {
    id: 16,
    name: "",
    pic: "/public/Products/Lighting/16.jpg",
    path: "",
  },
  {
    id: 17,
    name: "",
    pic: "/public/Products/Lighting/17.jpg",
    path: "",
  },
  {
    id: 18,
    name: "",
    pic: "/public/Products/Lighting/18.jpg",
    path: "",
  },
  {
    id: 19,
    name: "",
    pic: "/public/Products/Lighting/19.jpg",
    path: "",
  },
  {
    id: 20,
    name: "",
    pic: "/public/Products/Lighting/20.jpg",
    path: "",
  },
  {
    id: 21,
    name: "",
    pic: "/public/Products/Lighting/21.jpg",
    path: "",
  },
  {
    id: 22,
    name: "",
    pic: "/public/Products/Lighting/22.jpg",
    path: "",
  },
  {
    id: 23,
    name: "",
    pic: "/public/Products/Lighting/23.jpg",
    path: "",
  },
  {
    id: 24,
    name: "",
    pic: "/public/Products/Lighting/24.jpg",
    path: "",
  },
  {
    id: 25,
    name: "",
    pic: "/public/Products/Lighting/25.jpg",
    path: "",
  },
  {
    id: 26,
    name: "",
    pic: "/public/Products/Lighting/26.jpg",
    path: "",
  },
  {
    id: 27,
    name: "",
    pic: "/public/Products/Lighting/27.jpg",
    path: "",
  },
  {
    id: 28,
    name: "",
    pic: "/public/Products/Lighting/28.jpg",
    path: "",
  },
  {
    id: 29,
    name: "",
    pic: "/public/Products/Lighting/29.jpg",
    path: "",
  },
  {
    id: 30,
    name: "",
    pic: "/public/Products/Lighting/30.jpg",
    path: "",
  },
  {
    id: 31,
    name: "",
    pic: "/public/Products/Lighting/31.jpg",
    path: "",
  },
  {
    id: 32,
    name: "",
    pic: "/public/Products/Lighting/32.jpg",
    path: "",
  },
  {
    id: 33,
    name: "",
    pic: "/public/Products/Lighting/33.jpg",
    path: "",
  },
  {
    id: 34,
    name: "",
    pic: "/public/Products/Lighting/34.jpg",
    path: "",
  },
  {
    id: 35,
    name: "",
    pic: "/public/Products/Lighting/35.jpg",
    path: "",
  },
  {
    id: 36,
    name: "",
    pic: "/public/Products/Lighting/36.jpg",
    path: "",
  },
  {
    id: 37,
    name: "",
    pic: "/public/Products/Lighting/37.jpg",
    path: "",
  },
  {
    id: 38,
    name: "",
    pic: "/public/Products/Lighting/38.jpg",
    path: "",
  },
  {
    id: 39,
    name: "",
    pic: "/public/Products/Lighting/39.jpg",
    path: "",
  },
  {
    id: 40,
    name: "",
    pic: "/public/Products/Lighting/40.jpg",
    path: "",
  },
  {
    id: 41,
    name: "",
    pic: "/public/Products/Lighting/41.jpg",
    path: "",
  },
  {
    id: 42,
    name: "",
    pic: "/public/Products/Lighting/42.jpg",
    path: "",
  },
  {
    id: 43,
    name: "",
    pic: "/public/Products/Lighting/43.jpg",
    path: "",
  },
  {
    id: 44,
    name: "",
    pic: "/public/Products/Lighting/44.jpg",
    path: "",
  },
  {
    id: 45,
    name: "",
    pic: "/public/Products/Lighting/45.jpg",
    path: "",
  },
  {
    id: 46,
    name: "",
    pic: "/public/Products/Lighting/46.jpg",
    path: "",
  },
  {
    id: 47,
    name: "",
    pic: "/public/Products/Lighting/47.jpg",
    path: "",
  },
  {
    id: 48,
    name: "",
    pic: "/public/Products/Lighting/48.jpg",
    path: "",
  },
  {
    id: 49,
    name: "",
    pic: "/public/Products/Lighting/49.jpg",
    path: "",
  },
];

// in the lightening 4 categores :